version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3037:3000'
      - '5517:5555'
    volumes:
      - ./realDb:/app/realDb
      - ./uploads:/app/uploads
    environment:
      DATABASE_URL: ${DATABASE_URL}
    command: "npm run start"
    restart: always